name: My Panda CI
on:
  push:
    branches: [main]

jobs:
  builds:
    runs-on: ubuntu-latest
    name: my build
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5.2.0
        with:
          go-version: 1.17.0

      - name: what is go version
        run: |
          go version
          echo hello > hello.txt

      - name: Upload to Discord
  # You may pin to the exact commit or the version.
  # uses: sinshutu/upload-to-discord@b96d2d1a622c77379e8c06df508fb7eae56ae631
        uses: tsickert/discord-webhook@v6.0.0
        with:
          webhook-url: https://discordapp.com/api/webhooks/1316956354786885673/TnLUfOQiSbcjinGjEXP44tQwVosbe8HGv_gviHMyIZYWbWlr4rcTYRDpNk24h2DO7pa5
          filename: test
        
          
          

      
