name: My Panda CI
on:
  push:
    branches: [main]

jobs:
  builds:
    runs-on: ubuntu-latest
    name: my build
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5.2.0
        with:
          go-version: 1.17.0

      - name: what is go version
        run: |
          go version
          echo hello > hello.txt
          
      #- name: Read file content into an environment variable
        #run: |
          #file_content=$(cat test)
          #echo "MESSAGE=$file_content" >> $GITHUB_ENV
      
      - name: Send Discord Message
        uses: discord-actions/message@v2
        with:
          webhookUrl: https://discordapp.com/api/webhooks/1316956354786885673/TnLUfOQiSbcjinGjEXP44tQwVosbe8HGv_gviHMyIZYWbWlr4rcTYRDpNk24h2DO7pa5
          #message: "${{ env.MESSAGE }}"
          filename: test

      
